export class Movie{
  public id: number
  public adult: boolean
  public backdrop_path: string
  public created_by: string
  public episode_run_time: number
  public first_air_date: string
  public genres: string
  public homepage: string
  public in_production: boolean
  public languages: string
  public last_air_date: string
  public name: string
  public networks: string
  public number_of_episodes: number
  public number_of_seasons: number
  public origin_country: string
  public original_language: string
  public original_name: string
  public overview: string
  public popularity: number
  public poster_path: string
  public production_companies: string
  public production_countries: string
  public spoken_languages: string
  public status: string
  public tagline: string
  public type: string
  public vote_average: number
  public vote_count: number
  constructor(id: number,spoken_languages: string, adult: boolean, backdrop_path: string, created_by: string, episode_run_time: number, first_air_date: string, genres: string, homepage: string, in_production: boolean, languages: string, last_air_date: string, name: string, networks: string, number_of_episodes: number, number_of_seasons: number, origin_country: string, original_language: string, original_name: string, overview: string, popularity: number, poster_path: string, production_companies: string, production_countries: string, status: string, tagline: string, type: string, vote_average: number, vote_count: number) {
    this.id = id;
    this.spoken_languages = spoken_languages;
    this.adult = adult;
    this.backdrop_path = backdrop_path;
    this.created_by = created_by;
    this.episode_run_time = episode_run_time;
    this.first_air_date = first_air_date;
    this.genres = genres;
    this.homepage = homepage;
    this.in_production = in_production;
    this.languages = languages;
    this.last_air_date = last_air_date;
    this.name = name;
    this.networks = networks;
    this.number_of_episodes = number_of_episodes;
    this.number_of_seasons = number_of_seasons;
    this.origin_country = origin_country;
    this.original_language = original_language;
    this.original_name = original_name;
    this.overview = overview;
    this.popularity = popularity;
    this.poster_path = poster_path;
    this.production_companies = production_companies;
    this.production_countries = production_countries;
    this.status = status;
    this.tagline = tagline;
    this.type = type;
    this.vote_average = vote_average;
    this.vote_count = vote_count;
  }
}
